parameters:
- name: ostype
  type: string
  default: 'None'

steps:
- script: echo "ostype is ${{ parameters.ostype }}"
- ${{ if ne(parameters.ostype, 'mac-arm64') }}:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
- ${{ if ne(parameters.ostype, 'mac-arm64') }}:
  - task: Bash@3
    inputs:
      filePath: $(buildScript)
      arguments: $(buildScriptArgs)
- ${{ if eq(parameters.ostype, 'mac-arm64') }}:
  - task: UniversalPackages@0
    displayName: 'Download osx-arm64 package'
    inputs:
      command: download
      vstsFeed: 'Database Systems/azuredatastudio-mysql'
      vstsFeedPackage: 'mysqltoolsservice-osx-arm64'
      vstsPackageVersion: '0.0.1'
      downloadDirectory: '$(Build.SourcesDirectory)'
- ${{ if eq(parameters.ostype, 'mac-arm64') }}:
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.tar.gz'
      destinationFolder: $(Build.SourcesDirectory)/build