parameters:
- name: vmImage
  default: 'windows'
steps:
- ${{ if ne(parameters.vmImage, 'mac-arm64') }}:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
- ${{ if ne(parameters.vmImage, 'mac-arm64') }}:
  - task: Bash@3
    condition: ne(parameters.vmImage, 'mac-arm64')
    inputs:
      filePath: $(buildScript)
      arguments: $(buildScriptArgs)
- ${{ if eq(parameters.vmImage, 'mac-arm64') }}:
  - task: UniversalPackages@0
    displayName: 'Download osx-arm64 package'
    condition: eq(parameters.vmImage, 'mac-arm64')
    inputs:
      command: download
      vstsFeed: 'Database Systems/azuredatastudio-mysql'
      vstsFeedPackage: 'mysqltoolsservice-osx-arm64'
      vstsPackageVersion: '0.0.1'
      downloadDirectory: '$(Build.SourcesDirectory)'
- ${{ if eq(parameters.vmImage, 'mac-arm64') }}:
  - task: ExtractFiles@1
    condition: eq(parameters.vmImage, 'mac-arm64')
    inputs:
      archiveFilePatterns: '**/*.tar.gz'
      destinationFolder: $(Build.SourcesDirectory)/build