steps:
- task: UsePythonVersion@0
  condition: ne(variables['archiveFileName'], 'mysqltoolsservice-osx-arm64.tar.gz')
  inputs:
    versionSpec: '3.10'
- task: Bash@3
  condition: ne(variables['archiveFileName'], 'mysqltoolsservice-osx-arm64.tar.gz')
  inputs:
    filePath: $(buildScript)
    arguments: $(buildScriptArgs)
- task: UniversalPackages@0
  displayName: 'Download osx-arm64 package'
  condition: eq(variables['archiveFileName'], 'mysqltoolsservice-osx-arm64.tar.gz')
  inputs:
    command: download
    vstsFeed: 'Database Systems/azuredatastudio-mysql'
    vstsFeedPackage: 'mysqltoolsservice-osx-arm64'
    vstsPackageVersion: '0.0.1'
    downloadDirectory: '$(Build.SourcesDirectory)' 
- task: ExtractFiles@1
  condition: eq(variables['archiveFileName'], 'mysqltoolsservice-osx-arm64.tar.gz')
  inputs:
    archiveFilePatterns: '**/*.tar.gz'
    destinationFolder: $(Build.SourcesDirectory)/build