steps:
- task: UsePythonVersion@0
  condition: ${{ ne(parameters.platform, 'mac-arm64') }}
  inputs:
    versionSpec: '3.10'
- task: Bash@3
  condition: ne('${{ parameters.platform }}', 'mac-arm64')
  inputs:
    filePath: $(buildScript)
    arguments: $(buildScriptArgs)