trigger: none
pr: none
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
      buildTemplate: 'templates\build.yml'
      buildScript: 'scripts/build-linux.sh'
      codesignTemplate: 'templates\codesign-linux.yml'
      archiveFileName: 'mysqltoolsservice-linux-x64.tar.gz'
      archiveType: 'tar'
    ubuntu22:
      imageName: 'ubuntu-22.04'
      buildTemplate: 'templates\build.yml'
      buildScript: 'scripts/build-linux.sh'
      codesignTemplate: 'templates\codesign-linux.yml'
      archiveFileName: 'mysqltoolsservice-ubuntu22-x64.tar.gz'
      archiveType: 'tar'
    mac-x64:
      imageName: 'macOS-latest'
      buildTemplate: 'templates\build.yml'
      buildScript: 'scripts/build-mac.sh'
      codesignTemplate: 'templates\codesign-linux.yml'
      archiveFileName: 'mysqltoolsservice-osx.tar.gz'
      archiveType: 'tar'
    mac-arm64:
      imageName: 'macOS-latest'
      buildTemplate: 'templates\build-mac-arm64.yml'
      codesignTemplate: 'templates\codesign-linux.yml'
      archiveFileName: 'mysqltoolsservice-osx-arm64.tar.gz'
      archiveType: 'tar'
    windows:
      imageName: 'windows-latest'
      buildTemplate: 'templates\build.yml'
      buildScript: 'scripts/build.sh'
      codesignTemplate: 'templates\codesign-windows.yml'
      archiveFileName: 'mysqltoolsservice-win-x64.zip'
      archiveType: 'zip'
pool:
  vmImage: $(imageName)
steps:
- template: $(buildTemplate)
- template: $(codesignTemplate)
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/mysqltoolsservice'
    Contents: 'CodeSignSummary*.md'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build/mysqltoolsservice'
    includeRootFolder: true
    archiveType: '$(archiveType)'
    archiveFile: '$(Build.SourcesDirectory)/build/$(archiveFileName)'
    replaceExistingArchive: true
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'build/$(archiveFileName)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: build