trigger: none
pr: none
strategy:
  matrix:
    mac:
      imageName: 'macOS-latest'
      buildScript: 'scripts/build-mac.sh'
      archiveFileName: 'mysqltoolsservice-osx.tar.gz'
      archiveType: 'tar'
pool:
  vmImage: $(imageName)
steps:
- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    command: download
    vstsFeed: 'Database Systems/azuredatastudio-mysql'
    vstsFeedPackage: 'mysqltoolsservice-osx-arm'
    vstsPackageVersion: '0.0.1'
    downloadDirectory: '$(Build.SourcesDirectory)/build' 
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/*.tar.gz'
    destinationFolder: $(Build.SourcesDirectory)/build
- task: CmdLine@2
  inputs:
    script: |
      cd '$(Build.SourcesDirectory)/build'
      ls