# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
      buildScript: 'scripts/build-linux.sh'
      buildScriptArgs: ''
      archiveType: 'tar'
    ubuntu22:
      imageName: 'ubuntu-22.04'
      buildScript: 'scripts/build-linux.sh'
      buildScriptArgs: 'ubuntu22'
      archiveType: 'tar'
    mac:
      imageName: 'macOS-latest'
      buildScript: 'scripts/build-mac.sh'
      buildScriptArgs: ''
      archiveType: 'tar'
    windows:
      imageName: 'windows-latest'
      buildScript: 'scripts/build.sh'
      buildScriptArgs: ''
      archiveType: 'zip'
pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
- task: Bash@3
  inputs:
    filePath: $(buildScript)
    arguments: $(buildScriptArgs)
- task: ArchiveFiles@2
  inputs:
    rootFolderorFile: '$(Build.SourcesDirectory)/build/mysqltoolsservice'
    archiveType: $(archiveType)