trigger: none
pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
- task: Bash@3
  inputs:
    filePath: 'scripts/build.sh'
    arguments: ''
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'Sign out code'
  inputs:
    ConnectedServiceName: 'Database System ESRP Connector'
    FolderPath: '$(Build.SourcesDirectory)/build/mysqltoolsservice'
    Pattern: |
      *.exe
      *.dll
    useMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
          {
            "parameterName": "OpusName",
            "parameterValue": "Azure Data Studio"
          },
          {
            "parameterName": "OpusInfo",
            "parameterValue": "https://github.com/microsoft/azuredatastudio"
          },
          {
            "parameterName": "PageHash",
            "parameterValue": "/NPH"
          },
          {
            "parameterName": "FileDigest",
            "parameterValue": "/fd sha256"
          },
          {
            "parameterName": "TimeStamp",
            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
          }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        },
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolVerify",
          "parameters": [
          {
            "parameterName": "VerifyAll",
            "parameterValue": "/all"
          }
                ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: 600
    MaxConcurrency: 5
    MaxRetryAttempts: 20
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      build/*.zip
      build/*.tar.gz
      build/mysqltoolsservice*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: build